services:
  postgres-db:
    image: postgres:15.3
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    restart: always
    env_file: .env.prod
    ports:
      - 3000:3000
    depends_on:
      - postgres-db

  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

networks:
  default:
    driver: bridge